#!/bin/bash

function c()  { gcc -static -o $*; }
function cc() { g++ -static -o $*; }
function T()  { exe=$1; file=$2; ${file#*.} $exe $file; }

T a inf_loop.c
T b mem_sink.cc
T c segfault.c
T d sigint.c
T e good_vector_1e4_rep.cc
T f good_vector_1e6.cc
T g good_vector_1e7.cc
T h good_vector_1e8.cc
T i good_vector_1e7_clear.cc
T j open_file.cc

